# .goreleaser.yml
# Build customization
project_name: plummy

builds:
  - binary: plantuml
    main: ./cmd/plantuml
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    ldflags: '-s -w -X main.version={{.Version}} -X main.buildDate={{.Date}}'
changelog:
  filters:
    exclude:
      - Merge pull request
      - Merge branch
checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}.sha256'

archive:
  name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}'
  format_overrides:
    - goos: windows
      format: zip
