# .goreleaser.yml
# Build customization
project_name: plummy

env:
  - CGO_ENABLED=0

builds:
  - id: ditaa
    binary: ditaa
    main: ./cmd/ditaa
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X github.com/rakutentech/plummy/plummy-cli/cli.Version={{.Version}}
      - -X github.com/rakutentech/plummy/plummy-cli/cli.CommitHash={{.Commit}}
      - -X github.com/rakutentech/plummy/plummy-cli/cli.BuildDate={{.Date}}
  - id: plantuml
    binary: plantuml
    main: ./cmd/plantuml
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X github.com/rakutentech/plummy/plummy-cli/cli.Version={{.Version}}
      - -X github.com/rakutentech/plummy/plummy-cli/cli.CommitHash={{.Commit}}
      - -X github.com/rakutentech/plummy/plummy-cli/cli.BuildDate={{.Date}}
changelog:
  filters:
    exclude:
      - Merge pull request
      - Merge branch
      -
checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}.sha256'

archives:
  - id: main
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip
