name: build

on:
  pull_request:
    branches:
      - '**'
    tags-ignore:
      - v*
  push:
    branches:
      - '**'
    tags-ignore:
      - v*

jobs:
  build-daemon:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Build daemon
        env:
          GITHUB_USERNAME: boazy
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cd plummy-daemon && ./gradlew build
  build-cli:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      -
        name: Run GoReleaser
        uses: boazy/goreleaser-action@master
        with:
          version: v0.123.3
          args: release --skip-publish
          workdir: plummy-cli/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
