name: goreleaser

on:
  pull_request:
  push:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      -
        name: Run GoReleaser
        uses: boazy/goreleaser-action@master
        with:
          version: v0.123.3
          args: release
          subdir: plummy-cli/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
