name: tagged-release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Publish daemon JAR
        env:
          GITHUB_USERNAME: boazy
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cd plummy-daemon && ./gradlew publish
